### ISSUE TITLE
درخواست افزودن کانال

### ISSUE THREAD

**Issue by Farzadbayan** [omid/awesome-persian-youtubers#13]
آدرس کانال: https://youtube.com/farzadbayan

توضیحات:
ایده‌هایی نو برای ارتباط بهتر با خودمون و دیگران

**Comment by omid** [comment]
ممنون، اضافه شد.
اما باید تعداد اعضا رو پابلیک کنی و باید تعداد بیشتر از ۱۰ باشه تا توی لیست دیده بشه.

لیست هر شب آپدیت می‌شه به صورت خودکار.
