### ISSUE TITLE
Json or Yaml output 

### ISSUE THREAD

**Issue by pesarkhobeee** [omid/awesome-persian-youtubers#16]
Dear awesome-persian-youtubers folk,

I was thinking about displaying the list of Persian youtubers in my website. 
In order to do that it will be wonderful if you generate a general output in an standard format like Json or YAML right beside of your readme file.

Kind regards,
Farid

**Comment by omid** [comment]
Thanks for the cool idea.

Done. You can find them here:
A new list will be generated every day.

https://github.com/omid/awesome-persian-youtubers/tree/master/export
